esphome:
  name: garage

esp8266:
  board: esp07

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

# OTA is required for Over-the-Air updating
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret gararge_ssid
    password: !secret gararge_password

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

uart:
  baud_rate: 115200
  tx_pin: 1
  rx_pin: 3

switch:
  - platform: uart
    name: "Open"
    id: openBtn
    data: ">0a"
    icon: "mdi:garage-open-variant"

  - platform: uart
    name: "Stop"
    id: stopBtn
    data: ">1a"
    icon: "mdi:garage-alert-variant"

  - platform: uart
    name: "Close"
    id: closeBtn
    data: ">2a"
    icon: "mdi:garage-variant"
